CLUS-5247 add --backup-list option when deleting backups
severalnines/s9s-tools pull request #112
Opened 2024-12-19 21:47 UTC by alvaro-vinuela

2024-12-20 08:40 UTC, Piotr-S9s requested changes

2024-12-20 08:40 UTC, Piotr-S9s commented on libs9s/s9soptions.cpp
> +"  --backup-list=\"ID1, ID2\" The list of IDs of the backups.\n"
Please fix indentation, this line looks odd when compared to others in cmdline (at least mine)
`
--backup-id=ID             The ID of the backup.
--backup-list="ID1, ID2" The list of IDs of the backups.
--cluster-id=ID            The ID of the cluster.

`

2024-12-20 08:40 UTC, Piotr-S9s commented on libs9s/s9srpcclient.cpp
> +        PRINT_ERROR(
I recall that getopt can sometimes do best effort to match options.

2024-12-20 08:40 UTC, Piotr-S9s commented on libs9s/s9srpcclient.cpp
> +                "The options --backup-id and --backup-id-list are exclusive"
```suggestion
                "The options --backup-id and --backup-list are exclusive"
```

2024-12-20 08:40 UTC, Piotr-S9s commented on libs9s/s9srpcclient.cpp
> +
empty line not needed

2025-01-09 08:53 UTC, alvaro-vinuela commented on libs9s/s9soptions.cpp
> +"  --backup-list=\"ID1, ID2\" The list of IDs of the backups.\n"
Looks better now, right
![image](https://github.com/user-attachments/assets/7715e1bb-3673-4d70-bf80-fa4c8fe6960e)

2025-01-09 09:08 UTC, Piotr-S9s approved these changes

2025-01-09 09:18 UTC, merged